[package]
name = "rust_plugin_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
external_contracts = { git = "https://github.com/extendmepls/external_contracts" }
